Repository uLucasFraga/cypress_api_for_studies, pull requests merged in 2021-04, with the labels that each got.

#2 Iniciando projeto do cypress para API
  .github/pull_request_template.md
  .github/workflows/dev.yml
  .github/workflows/qa.yml
  .gitignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/tests/login/login.spec.js
  cypress/integration/tests/users/users.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  cypress/support/requests.js
  package.json
Labels: documentation, don't delete, working in progress

#4 lint
  .github/workflows/dev.yml
  cypress/integration/tests/login/login.spec.js
  cypress/integration/tests/usuarios/usuarios.spec.js
  cypress/support/requests.js
  cypress/support/session.js
  package.json
Labels: don't delete, ready for review

#6 Atualizando projeto
  .cypress.env.example
  .env.example
  .github/workflows/dev.yml
  .gitignore
  README.md
  cypress/fixtures/usuarios.json
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/support/credentials.js
  cypress/support/index.js
  cypress/support/requests.js
  cypress/support/session.js
  package-lock.json
  package.json
Labels: bug, don't delete, ready for review

#7 Resolver problema no run do cypress
  .github/workflows/dev.yml
Labels: bug, ready for review

#8 alterando yaml
  .github/workflows/dev.yml
  README.md
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/plugins/index.js
  cypress/support/credentials.js
  cypress/support/index.js
  cypress/support/requests.js
  package-lock.json
  package.json
Labels: bug, don't delete, ready for review

#9 alterando ci
  .github/workflows/dev.yml
  package.json
Labels: don't delete, enhancement, working in progress

#10 Novos cenários de testes - get usuarios
  README.md
  cypress/integration/tests/usuarios/get.spec.js
Labels: don't delete, ready for review

#11 Criação de novos cenários - PUT
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/integration/tests/usuarios/post.spec.js
  cypress/integration/tests/usuarios/put.spec.js
  cypress/plugins/index.js
  cypress/support/credentials.js
  cypress/support/index.js
  cypress/support/requests.js
  package.json
Labels: don't delete, ready for review

#12 Criando cenarios de deletar usuario
  cypress/integration/tests/usuarios/delete.spec.js
Labels: don't delete, ready for review

#13 Criando testes para Produtos
  cypress/fixtures/products.json
  cypress/integration/tests/produtos/get.spec.js
  cypress/support/requests.js
Labels: don't delete, ready for review

#14 Criação de cenários do verbo POST - Produtos
  cypress/integration/tests/produtos/get.spec.js
  cypress/integration/tests/produtos/post.spec.js
  cypress/support/requests.js
Labels: don't delete, ready for review

#15 lint
  cypress/fixtures/usuarios.json
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/post.spec.js
Labels: don't delete, ready for review

#16 Criando cenários para verbo PUT - Produtos
  cypress/fixtures/produtos.json
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/produtos/get.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/post.spec.js
Labels: don't delete, working in progress

#18 Melhorias necessárias para CI e scripts
  .github/workflows/dev.yml
  README.md
  package-lock.json
  package.json
Labels: don't delete, ready for review

#19 Criando novos cenários de editar Produto
  cypress/fixtures/produtos.json
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/produtos/get.spec.js
  cypress/integration/tests/produtos/post.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/integration/tests/usuarios/post.spec.js
  cypress/integration/tests/usuarios/put.spec.js
  cypress/support/requests.js
Labels: don't delete, ready for review

#20 Criando novo cenário de testes de DELETAR Produto
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/produtos/delete.spec.js
  cypress/integration/tests/produtos/post.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/post.spec.js
  cypress/support/requests.js
  package-lock.json
Labels: don't delete, ready for review

#21 Criando novos cenários de testes para o verbo GET em Carrinhos
  cypress/fixtures/carrinhos.json
  cypress/integration/tests/carrinhos/get.spec.js
  cypress/integration/tests/produtos/delete.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/put.spec.js
  cypress/support/requests.js
Labels: don't delete, ready for review

#22 Cenários verbo POST - Carrinhos
  cypress/integration/tests/carrinhos/get.spec.js
  cypress/integration/tests/carrinhos/post.spec.js
  cypress/support/credentials.js
  cypress/support/requests.js
Labels: don't delete, ready for review
