Repository uLucasFraga/cypress_api_for_studies, pull requests merged in 2021-05, with the labels that each got.

#23 Criando cenários de testes do verbo DELETE - carrinhos
  cypress/integration/tests/carrinhos/delete.spec.js
  cypress/integration/tests/carrinhos/get.spec.js
  cypress/integration/tests/carrinhos/post.spec.js
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/produtos/delete.spec.js
  cypress/integration/tests/produtos/get.spec.js
  cypress/integration/tests/produtos/post.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/integration/tests/usuarios/post.spec.js
  cypress/integration/tests/usuarios/put.spec.js
  cypress/support/requests.js
Labels: don't delete, ready for review

#24 Update ci.yml
  .github/workflows/ci.yml
Labels: ready for review

#27 Implementando allure report
  .github/workflows/ci.yml
  .gitignore
  cypress.json
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/plugins/index.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: bug, don't delete, ready for review, working in progress

#28 novo readme
  .github/workflows/ci.yml
  .gitignore
  README.md
  package.json
Labels: documentation, don't delete, ready for review

#29 alterando nome
  .github/workflows/ci.yml
  README.md
Labels: documentation, don't delete, ready for review

#30 Testando rodar cypress em paralelo no ci
  .github/workflows/ci.yml
  cypress/integration/tests/carrinhos/delete.spec.js
  cypress/integration/tests/carrinhos/get.spec.js
  cypress/integration/tests/carrinhos/post.spec.js
  cypress/integration/tests/login/post.spec.js
  cypress/integration/tests/produtos/delete.spec.js
  cypress/integration/tests/produtos/get.spec.js
  cypress/integration/tests/produtos/post.spec.js
  cypress/integration/tests/produtos/put.spec.js
  cypress/integration/tests/usuarios/delete.spec.js
  cypress/integration/tests/usuarios/get.spec.js
  cypress/integration/tests/usuarios/post.spec.js
  cypress/integration/tests/usuarios/put.spec.js
  package-lock.json
  package.json
Labels: don't delete, ready for review, working in progress

#31 testando - devo apagar.
  .github/workflows/ci.yml
Labels: bug, ready for review

#32 deletando lib
  package.json
Labels: bug, don't delete, ready for review
